spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:63792}
    cache:
      type: redis
      redis:
        time-to-live: PT30M
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://admin:admin@localhost:27017/offers

offer:
  http:
    client:
      config:
        connectionTimeout: 2000
        port: 5057
        readTime: 5000
        uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com

http:
  offers:
    scheduler:
      request:
        delay: PT3H

scheduling:
  enabled: true

auth:
  jwt:
    secret: QxJdy3V2hmPSmeNyiiP8a8Ms1AbYwfhFaV8qrh9yR+6aBVa0TTvg3saRL1my34SP
    expirationDays: 30
    issuer: job-offers-backend
