spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/offers

offer:
  http:
    client:
      config:
        connectionTimeout: 2000
        port: 5057
        readTime: 5000
        uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com:5057/offers


http:
  offers:
    scheduler:
      request:
        delay: PT3M